{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "deployment-tracker.fullname" . }}-ingress
  labels:
    {{- include "deployment-tracker.labels" . | nindent 4 }}

spec:
  podSelector:
    matchLabels:
      {{- include "deployment-tracker.selectorLabels" . | nindent 6 }}

  policyTypes:
    - Ingress

  ingress:
    - from:
        - podSelector:
            matchLabels:
              access: deployment-tracker

      ports:
        - protocol: TCP
          port: 8000
{{- end }}
