apiVersion: v1
kind: Service
metadata:
  name: deployment-tracker
spec:
  type: {{ .Values.service.type }}

  selector:
    app: deployment-tracker

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
