replicaCount: 2

image:
  repository: ghcr.io/iiismailtriki/deployment-tracker
  digest: sha256:bf548c5f35dbcf04407da0787b224c3aa3838a3c6486a971714fe83d020e23d5
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-pull-secret

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

networkPolicy:
  enabled: true
